#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: cpan
# autospec version: v21
# autospec commit: 94c6be0
#
Name     : perl-Term-ProgressBar
Version  : 2.23
Release  : 22
URL      : https://cpan.metacpan.org/authors/id/M/MA/MANWAR/Term-ProgressBar-2.23.tar.gz
Source0  : https://cpan.metacpan.org/authors/id/M/MA/MANWAR/Term-ProgressBar-2.23.tar.gz
Source1  : http://http.debian.net/debian/pool/main/libt/libterm-progressbar-perl/libterm-progressbar-perl_2.22-1.debian.tar.xz
Summary  : 'provide a progress meter on a standard terminal'
Group    : Development/Tools
License  : Artistic-1.0 Artistic-1.0-Perl GPL-1.0
Requires: perl-Term-ProgressBar-license = %{version}-%{release}
Requires: perl-Term-ProgressBar-perl = %{version}-%{release}
BuildRequires : buildreq-cpan
BuildRequires : perl(Capture::Tiny)
BuildRequires : perl(Class::MethodMaker)
BuildRequires : perl(Sub::Uplevel)
BuildRequires : perl(Term::ReadKey)
BuildRequires : perl(Test::Exception)
BuildRequires : perl(Test::Warnings)
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
Module Term-ProgressBar (2.09):
Description:
A progress bar for things that take a while.  It looks like

%package dev
Summary: dev components for the perl-Term-ProgressBar package.
Group: Development
Provides: perl-Term-ProgressBar-devel = %{version}-%{release}
Requires: perl-Term-ProgressBar = %{version}-%{release}

%description dev
dev components for the perl-Term-ProgressBar package.


%package license
Summary: license components for the perl-Term-ProgressBar package.
Group: Default

%description license
license components for the perl-Term-ProgressBar package.


%package perl
Summary: perl components for the perl-Term-ProgressBar package.
Group: Default
Requires: perl-Term-ProgressBar = %{version}-%{release}

%description perl
perl components for the perl-Term-ProgressBar package.


%prep
%setup -q -n Term-ProgressBar-2.23
cd %{_builddir}
tar xf %{_sourcedir}/libterm-progressbar-perl_2.22-1.debian.tar.xz
cd %{_builddir}/Term-ProgressBar-2.23
mkdir -p deblicense/
cp -r %{_builddir}/debian/* %{_builddir}/Term-ProgressBar-2.23/deblicense/

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
if test -f Makefile.PL; then
%{__perl} -I. Makefile.PL
make  %{?_smp_mflags}
else
%{__perl} Build.PL
./Build
fi

%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make TEST_VERBOSE=1 test

%install
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/perl-Term-ProgressBar
cp %{_builddir}/debian/copyright %{buildroot}/usr/share/package-licenses/perl-Term-ProgressBar/6b82dd97700b37596cd3816893ddfc6d34a73081 || :
if test -f Makefile.PL; then
make pure_install PERL_INSTALL_ROOT=%{buildroot} INSTALLDIRS=vendor
else
./Build install --installdirs=vendor --destdir=%{buildroot}
fi
find %{buildroot} -type f -name .packlist -exec rm -f {} ';'
find %{buildroot} -depth -type d -exec rmdir {} 2>/dev/null ';'
find %{buildroot} -type f -name '*.bs' -empty -exec rm -f {} ';'
%{_fixperms} %{buildroot}/*

%files
%defattr(-,root,root,-)

%files dev
%defattr(-,root,root,-)
/usr/share/man/man3/Term::ProgressBar.3
/usr/share/man/man3/Term::ProgressBar::IO.3

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/perl-Term-ProgressBar/6b82dd97700b37596cd3816893ddfc6d34a73081

%files perl
%defattr(-,root,root,-)
/usr/lib/perl5/*
